services:
  node-red:
    image: nodered/node-red:latest
    container_name: shelter-nodered
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - node_red_data:/data
    # ESTO ES NECESARIO PARA QUE NODE-RED HABLE CON TU JAVA EN WINDOWS/LINUX
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_red_data:
